path: .dataset/VisDrone_Dataset

train: VisDrone2019-DET-train/images
val: VisDrone2019-DET-val/images
test: VisDrone2019-DET-test-dev/images

nc: 2

names:
  0: human
  1: car

cleaning:
  clip_coords: true
  convert_to_obb: true